### ISSUE TITLE
We can't toggle the service

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/spring-boot-circuit-breaker-booster#3]
When we click on the `toggle` button this error is reported within the console of the web browser and the service is not stopped

![screenshot 2017-06-14 17 40 41](https://user-images.githubusercontent.com/463790/27141549-cb0d615e-5128-11e7-8979-39171cbfa0f4.png)

@alesj Have you tested the project on Openshift ?

**Comment by alesj** [comment]
@cmoulliard check now -- managed to get my old fix committed (long story ... :-)

**Comment by metacosm** [comment]
@alesj @cmoulliard what's the status of this?

**Comment by cmoulliard** [comment]
Fixed
